name: 'Electronegativity'
description: 'Electronegativity is a tool to identify misconfigurations and security anti-patterns in Electron applications.'
branding:
  icon: 'check-circle'
  color: 'purple'
inputs:
  input:
    description: --input argument. See https://github.com/doyensec/electronegativity/blob/master/README.md#cli
    required: false
    default: '.'
  severity:
    description: --severity argument. See https://github.com/doyensec/electronegativity/blob/master/README.md#cli
    required: false
    default: ''
  confidence:
    description: --confidence argument. See https://github.com/doyensec/electronegativity/blob/master/README.md#cli
    required: false
    default: ''
  checks:
    description: --checks argument. See https://github.com/doyensec/electronegativity/blob/master/README.md#cli
    required: false
    default: ''
  exclude-checks:
    description: --exclude-checks argument. See https://github.com/doyensec/electronegativity/blob/master/README.md#cli
    required: false
    default: ''
  upgrade:
    description: --upgrade argument. See https://github.com/doyensec/electronegativity/blob/master/README.md#cli
    required: false
    default: ''
  electron-version:
    description: --electron-version argument. See https://github.com/doyensec/electronegativity/blob/master/README.md#cli
    required: false
    default: ''
  parser-plugins:
    description: --parser-plugins argument. See https://github.com/doyensec/electronegativity/blob/master/README.md#cli
    required: false
    default: ''
runs:
  using: "composite"
  steps:
      - name: 'Electronegativity checkout'
        uses: actions/checkout@v2
        with:
          repository: 'jarlob/electronegativity'
          ref: sarif2
          path: electronegativity
         
      - name: 'Install electronegativity'
        run: |
          cd electronegativity
          npm install
          npm run build
          cd ..
          # npm install @doyensec/electronegativity -g
          
      - name: 'Run electronegativity'
        run: |
          mkdir ../results
          if [[ "${{ inputs.input }}" != "" ]]; then
            input="-i ${{ inputs.input }}"
          fi
          if [[ "${{ inputs.checks }}" != "" ]]; then
            checks="--checks ${{ inputs.checks }}"
          fi
          if [[ "${{ inputs.exclude-checks }}" != "" ]]; then
            excludechecks="--exclude-checks ${{ inputs.exclude-checks }}"
          fi
          node ./electronegativity/dist/index.js -r -o ../results/out.sarif $input $checks $excludechecks

      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ../results
